backend:
  name: git-gateway
  branch: main  # Use your branch name

media_folder: "public/images/uploads"  # Where uploaded images are stored
public_folder: "/images/uploads"  # Public path for images

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - name: "gallery"
        label: "Gallery"
        file: "content/gallery/gallery.json"
        format: "json"
        fields:
          - label: "Gallery Images"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "featured"
    label: "Featured Highlights"
    files:
      - name: "featured"
        label: "Featured Highlights"
        file: "content/featured/featured.json"
        format: "json"
        fields:
          - label: "Highlights"
            name: "highlights"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
