backend:
  name: git-gateway
  branch: main  # Change this if your branch is different

media_folder: "images/uploads"  # Where uploaded images are stored
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"  # Folder to store JSON data
    create: true
    format: json
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { l
