
backend:
  name: git-gateway
  branch: main  # Change this to your branch name if different

media_folder: "images/uploads"  # Where images are stored
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Gallery"
    delete: false
    editor:
      preview: false
    format: json
    file: "content/gallery/gallery.json"  # Saves all gallery entries in one JSON file
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text", required: false}
