backend:
  name: git-gateway
  branch: main  # Use your branch name

media_folder: "public/images/uploads"  # Where uploaded images are stored
public_folder: "/images/uploads"  # Public path for images

collections:
  - name: "gallery"
    label: "Gallery"
    file: "content/gallery/gallery.json"  # Stores everything in one JSON file
    format: "json"
    fields:
      - label: "Gallery Images"
        name: "gallery"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "text" }
