backend:
  name: git-gateway
  branch: main  # Change this if using a different branch

media_folder: "public/images/uploads"  # Where uploaded images are stored
public_folder: "/images/uploads"  # Public path for images

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"  # Auto-generate slug based on title
    format: "json"  # Saves as JSON file
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
