backend:
  name: git-gateway
  branch: main  # Use your branch name

media_folder: "public/images/uploads"  # Where uploaded images are stored
public_folder: "/images/uploads"  # Public path for images

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - name: "gallery"
        label: "Gallery"
        file: "content/gallery/gallery.json"
        format: "json"
        fields:
          - label: "Gallery Images"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "featured"
    label: "Featured Highlights"
    files:
      - name: "featured"
        label: "Featured Highlights"
        file: "content/featured/featured.json"
        format: "json"
        fields:
          - label: "Highlights"
            name: "highlights"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "recent-works"
    label: "Recent Works"
    files:
      - name: "recent-works"
        label: "Recent Works"
        file: "content/recent-works/recent-works.json"
        format: "json"
        fields:
          - label: "Works"
            name: "works"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "monthly-reports"
    label: "Monthly reports"
    files:
      - name: "monthly-reports"
        label: "Monthly reports"
        file: "content/monthly-reports.json"
        format: "json"
        fields:
          - label: "அறிக்கைகள்"
            name: "reports"
            widget: "list"
            fields:
              - { label: "வரவு வந்த மாதம்", name: "monthYear", widget: "string" }
              - { label: "நன்கொடை கொடுத்த நபர்கள்", name: "donors", widget: "number" }
              - { label: "வரவு", name: "income", widget: "string" }
              - { label: "பொருட்கள் கொடுத்த மாதம்", name: "distributionMonth", widget: "string" }
              - { label: "செலவு", name: "expense", widget: "string" }
              - { label: "மீதம் (அடுத்த மாதம் வரவில் சேர்க்கப்பட்டுள்ளது)", name: "remaining", widget: "string" }
              - { label: "கொடுத்த வீடுகள்", name: "familiesHelped", widget: "number" }

  - name: "donations"
    label: "Donations"
    description: "Donation records"
    format: "json"
    editor:
      preview: false
    files:
      - name: "donations"
        label: "Donations List"
        file: "donations.json"
        fields:
          - label: "Donations"
            name: "donations"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Amount", name: "amount", widget: "string" }
              - { label: "Transaction ID", name: "transactionId", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
