backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"  # Stores uploaded images
public_folder: "/images/uploads"       # How images are accessed

collections:
  - name: "gallery"
    label: "Gallery"
    format: "json"
    file: "content/gallery.json"  # Ensures ALL images are saved in ONE file
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text", required: false}
